# Generated by Django 5.0.6 on 2024-05-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theater_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["reservation"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "performance")},
        ),
    ]
