# Generated by Django 5.0.6 on 2024-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater_service", "0003_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                blank=True, to="theater_service.actor", verbose_name="actors"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                blank=True, to="theater_service.genre", verbose_name="genres"
            ),
        ),
    ]
