# Generated by Django 5.0.6 on 2024-05-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theater_service", "0004_alter_play_options_alter_play_actors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ["-show_time"]},
        ),
    ]
