# Generated by Django 5.0.6 on 2024-05-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theater_service", "0006_alter_ticket_performance_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
    ]
