# Generated by Django 5.0.6 on 2024-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater_service", "0007_alter_reservation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
